version: "2"

services:
  mongo:
    image: mongo:latest
    networks:
      - net

  web:
    build: ./
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - net
    depends_on:
      - mongo

networks:
  net:
